services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=devops_user
      - POSTGRES_PASSWORD=devops_pass
      - POSTGRES_DB=restaurant_db
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://devops_user:devops_pass@db:5432/restaurant_db

  frontend:
    build:
      context: ./frontend
      args:

        - REACT_APP_API_URL=/api

volumes:
  db_data:
